### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/michelmooij/TEX-bestanden/TeX-bes...

### ISSUE THREAD

**Issue by mooij009** [msiniscalchi/atom-latextools#24] opened 2016-01-25 12:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.7.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/michelmooij/TEX-bestanden/TeX-bestanden/Brief Askamp/BriefAskamp.log'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/michelmooij/TEX-bestanden/TeX-bestanden/Brief Askamp/BriefAskamp.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at /Users/michelmooij/.atom/packages/latextools/lib/builder.coffee:155:18
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -3:17.9.0 core:paste (atom-text-editor#latextools.darwin.texpath.editor.mini.is-focused)
     -0:56.4.0 latextools:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:15.5.0 editor:move-to-previous-subword-boundary (atom-text-editor.editor.is-focused)
     -0:01.2.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-writer",
      "markdown-preview-plus",
      "spell-check",
      "Zen",
      "autoflow",
      "latex-plus",
      "latex",
      "latex-completions",
      "latexer",
      "autocomplete-bibtex"
    ],
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  },
  "latextools": {
    "builderSettings": {
      "program": "xelatex"
    },
    "commandCompletion": "always",
    "darwin": {
      "texpath": "/usr/local/texlive/2015/bin/x86_64-darwin/xelatex"
    },
    "linux": {},
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latextools, v0.7.4
markdown-preview-opener, v0.1.1
markdown-table-formatter, v2.7.2
native-ui, v0.15.1
pandoc-convert, v1.0.4

# Dev
No dev packages
```

**Comment by ig0774** [comment] 2016-01-25 17:22
This is an error that should probably be made more informative. The cause, however, is that no log file is generated, presumably because latextools cannot find an executable it needs, which is probably a result of your `texpath` setting. 

Your `texpath` setting is `"/usr/local/texlive/2015/bin/x86_64-darwin/xelatex"`, i.e. it directly points to  the `xelatex` executable, which isn't going to work at all. `texpath` is used to supplement the system [`$PATH` variable](https://en.wikipedia.org/wiki/PATH_(variable)) (which, on recent versions of OS X, doesn't have much in it). As such, it is expected to point to a directory.

Please try setting your `texpath` setting to `/Library/TeX/texbin` or at least `"/usr/local/texlive/2015/bin/x86_64-darwin` and rebuild.

If you want to ensure that the plugin uses `xelatex`, you should have a directive at the top of your main file: `%!TEX program = xelatex` or set the `latextools.builderSettings.program` setting to `xelatex` in your config.

**Comment by msiniscalchi** [comment] 2016-01-25 17:43
Thanks @mooij009 and @ig0774. Part of the issue is that there are no detailed instructions for the package yet---my apologies. However, I've started drafting a "user manual" (based on the README for the Sublime Text version of the plugin, which is very comprehensive if a bit messy). Hopefully this will resolve ambiguities.

And yes, there shoudl also be better error reporting.

**Comment by msiniscalchi** [comment] 2016-01-25 21:10
I've pushed a small commit that should give a readable error message in case the log file can't be read for whatever reason. Closing.

**Closed by msiniscalchi** 2016-01-25 21:10 UTC

**Comment by mooij009** [comment] 2016-01-25 21:13
Thanks
