### ISSUE TITLE
fflush() failed  broken pipe

### ISSUE THREAD

**Issue by gkvallis** [msiniscalchi/atom-latextools#41] opened 2016-02-17 10:03 UTC
When compiling a file with latextools on a Mac (El Capitan) I get the following error:
  fflush() failed (Broken pipe)
    ==> Fatal error occurred, no output PDF file produced!
However, the file compiles perfectly well using the latexmk from the terminal, with exactly the same command and options, or using pdflatex directly. 

The same issue seems to have come up with atom-latex, where a solution was also given:
  https://github.com/thomasjo/atom-latex/issues/88
Perhaps the same issue is affecting latex tools?

**Comment by ig0774** [comment] 2016-02-27 12:09
It looks like `atom-latex` is basically using the same process `atom-latextools` is with the same flaws and all. I've created a PR to apply basically the same fix, but I'm unsure if it'll work because I can't duplicate the issue with any of the documents at my disposal. Still, it probably doesn't do any harm...

**Comment by msiniscalchi** [comment] 2016-03-04 20:29
Should be fixed in master. If you have a way to check (by pulling latextools from master rather than via the package manager), could you please check, and if the issue is resolved, close this? Thanks!

**Comment by gkvallis** [comment] 2016-03-05 11:19
I cannot reproduce the error with V 0.8. However, I cannot be absolutely sure the problem has disappeared because the error was delicate, and small changes would make it go away, and I no longer have the exact file that threw the original error. Okay with me to close this issue though.

**Comment by msiniscalchi** [comment] 2016-03-09 04:37
I'm reopening this because I noticed a considerable slowdown on OS X when building. THis goes away if the max buffer size is left unchanged. Can somebody else confirm this? @ig0774 ? This is not an issue on Windows btw.

At some level, there should be no need for a large buffer at all; if we can mute all output, that will also solve the problem. In any way, all error checking is done looking at the log file (and the return code).

**Comment by ig0774** [comment] 2016-03-09 06:27
@msiniscalchi: Weird. I don't notice a change in building time on OS X, but that could also just be an artefact of the documents I have, none of which produces all that much output.

You're, of course, absolutely right that under most circumstances, we don't actually need to buffer the output, since we read the output from the log. But when the log file itself doesn't get generated, it can be helpful to get some kind of feedback (e.g. as SublimeText/LaTeXTools#55 was intended to do). It may be a good idea, to change the way that we're invoking `latexmk` so that we pass `-silent` switch and change the `-interaction` flag to `batchmode`, which would greatly reduce the output, but still keep some output there in case it could be helpful... With those settings, we could (hopefully) go back to not needing to manipulate the maxBufferSize at all.

Regarding muting all output, the only real option I can see is to move from using `child_process.exec` to using `child_process.spawn`, since it's the only command that [supports setting the standard handlers](https://nodejs.org/api/child_process.html#child_process_options_stdio). All the other functions in `child_process` do some kind of buffering.

**Comment by msiniscalchi** [comment] 2016-03-10 20:07
@ig0774 @gkvallis I think the right way to fix this issue is to use `-interaction=batchmode`. This is a trivial change in the code. I would stay away from the `-silent` option, which implies `-c-style-errors`.

@gkvallis could you please make available one of the files that was giving you problems, so we can test? Maybe as a public Dropbox (or Google Drive) link?

**Comment by msiniscalchi** [comment] 2016-03-10 20:25
@ig0774 @gkvallis on the other hand, I am now seeing that the slowdowns *may* be related to pdf-view. So maybe just bumping up the buffer is the path of least resistance.

**Comment by gkvallis** [comment] 2016-03-11 08:08
Unfortunately I no longer have the exact files that gave me the problem. The issue was a bit delicate, and when I made some changes it went away. (It was a book-length document, using tufte-book.cls and > 100 figures, if that helps.)

pdf-view is indeed quite slow. I would like to use it but have gone back to skim for long documents.

Not quite the same issue, but could you put timing information in the console, so one can tell how long a document took to typeset?   All that is needed is the information that comes from: ‘time latexmk -pdf’ etc.



On 10 Mar 2016, at 20:07, msiniscalchi <notifications@github.com<mailto:notifications@github.com>> wrote:


@ig0774<https://github.com/ig0774> @gkvallis<https://github.com/gkvallis> I think the right way to fix this issue is to use -interaction=batchmode. This is a trivial change in the code. I would stay away from the -silent option, which implies -c-style-errors.

@gkvallis<https://github.com/gkvallis> could you please make available one of the files that was giving you problems, so we can test? Maybe as a public Dropbox (or Google Drive) link?

**Comment by msiniscalchi** [comment] 2016-04-29 14:37
Closing, as there seems to be no new action here.

**Closed by msiniscalchi** 2016-04-29 14:37 UTC
