### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/michelmooij/6.log'

### ISSUE THREAD

**Issue by mooij009** [msiniscalchi/atom-latextools#27] opened 2016-01-26 20:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.7.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/michelmooij/6.log'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/michelmooij/6.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at /Users/michelmooij/.atom/packages/latextools/lib/builder.coffee:155:18
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

### Commands

```
     -0:02.8.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  },
  "latextools": {
    "builder": "latex",
    "builderSettings": {
      "displayLog": true,
      "options": [
        "-f"
      ]
    },
    "commandCompletion": "always",
    "darwin": {
      "texpath": "/Library/TeX/texbin"
    },
    "linux": {},
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latex, v0.28.2
latexer, v0.2.7
latextools, v0.7.4
markdown-preview-opener, v0.1.1
markdown-table-formatter, v2.7.2
native-ui, v0.16.1

# Dev
No dev packages
```

**Comment by msiniscalchi** [comment] 2016-01-26 20:46
Closing, as this seems a duplicate of #28

**Closed by msiniscalchi** 2016-01-26 20:46 UTC
